package com.example.hot_or_cold;

import java.util.List;

/**
 * Class for /sessions get requests. This get request is used to gather information
 *  on all available data from each DE1 location, based on the location class
 *  , as well as the UserID of the person who made the get request, which might
 *  be automatically generated by the server if the user is new and entered 0 on the
 *  login screen. I learned all about get requests and retrofit from this youtube video:
 *  https://www.youtube.com/watch?v=4JGvDUlfk7Y&ab_channel=CodinginFlow
 */
public class Get_Request {

    /*
     randomly generated new UserID for new user, or previous UserID entered
     in the login screen, if it isn't a new user.
     */
    private int UserID;

    /*
      List of all DE1's currently in play, as well as their data (elaborated in
      Locations class)
     */
    private List<Locations> Sessions;


    public int getUserID() {
        return UserID;
    }

    public List<com.example.hot_or_cold.Locations> getLocations() {
        return Sessions;
    }

    public void setUserID(int userID) {
        UserID = userID;
    }
}


